version: '3.8'

services:
  marketing-alliance-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${MARKETING_ALLIANCE_DB_USERNAME}
      - POSTGRES_PASSWORD=${MARKETING_ALLIANCE_DB_PASSWORD}
      - POSTGRES_DB=${MARKETING_ALLIANCE_DB_DATABASE}
    ports:
      - "5984:5432"
    hostname: marketing-alliance-db

    volumes:
      - marketing-alliance-data:/var/lib/postgresql/data